import { Category, Tool } from "./types";

export const initialTools: Tool[] = [
  {
    name: "n8n",
    category: "Automation",
    description: "Visual workflow automation with extensible AI and API nodes.",
    useCase: "Connect AI services into repeatable operational workflows.",
    role: "Orchestration layer",
    alternatives: ["Zapier", "Make"],
    related: ["OpenAI", "Notion", "Supabase"],
    tags: ["workflows", "agents", "no-code"],
    notes: "Explore webhook triggers and agent tool calls next.",
    source: "YouTube / AI Stack",
    date: "May 27",
    importance: "High",
    viewed: "Today",
    pinned: true,
    favorite: true,
  },
  {
    name: "Cursor",
    category: "Coding",
    description: "AI-native code editor with contextual project assistance.",
    useCase: "Navigate, edit and reason about large codebases faster.",
    role: "Development workspace",
    alternatives: ["Windsurf", "GitHub Copilot"],
    related: ["MCP", "Claude", "GitHub"],
    tags: ["ide", "developer", "pairing"],
    notes: "Test custom rules for team coding standards.",
    source: "Product Hunt",
    date: "May 26",
    importance: "High",
    viewed: "Today",
    favorite: true,
  },
  {
    name: "Perplexity",
    category: "Research",
    description: "Citation-first discovery and answer engine.",
    useCase: "Explore unfamiliar topics with traceable sources.",
    role: "Research companion",
    alternatives: ["ChatGPT Search", "Elicit"],
    related: ["Notion", "Readwise", "Browser"],
    tags: ["search", "sources", "discovery"],
    notes: "Store high-value research threads alongside source URLs.",
    source: "Newsletter",
    date: "May 25",
    importance: "Medium",
    viewed: "Yesterday",
  },
  {
    name: "ElevenLabs",
    category: "Voice",
    description: "Natural speech generation and voice agent platform.",
    useCase: "Generate narration and conversational voice experiences.",
    role: "Voice output",
    alternatives: ["PlayHT", "Cartesia"],
    related: ["Descript", "HeyGen", "n8n"],
    tags: ["tts", "voice", "audio"],
    notes: "Compare latency for live assistant workflows.",
    source: "X bookmark",
    date: "May 23",
    importance: "Medium",
    viewed: "3 days ago",
  },
  {
    name: "Manus",
    category: "Agents",
    description: "Autonomous AI agent for multi-step digital tasks.",
    useCase: "Delegate research and deliverable-focused execution.",
    role: "Task agent",
    alternatives: ["Operator", "Genspark"],
    related: ["Browser", "Notion", "Slack"],
    tags: ["agent", "execution", "delegation"],
    notes: "Evaluate task reliability on recurring research briefs.",
    source: "Community",
    date: "May 21",
    importance: "Medium",
    viewed: "Last week",
  },
  {
    name: "Bolt",
    category: "Coding",
    description: "Prompt-to-application web development environment.",
    useCase: "Turn product ideas into working prototypes quickly.",
    role: "Prototype builder",
    alternatives: ["Lovable", "v0"],
    related: ["Supabase", "Vercel", "React"],
    tags: ["builder", "prototype", "web"],
    notes: "Useful for validation before production implementation.",
    source: "Demo day",
    date: "May 19",
    importance: "High",
    viewed: "Last week",
    pinned: true,
  },
];

export const catalog: Record<string, Omit<Tool, "name" | "date" | "viewed">> = {
  zapier: {
    category: "Automation",
    description: "No-code automation platform for app-to-app actions.",
    useCase: "Trigger reliable business workflows across common SaaS tools.",
    role: "Workflow connector",
    alternatives: ["n8n", "Make"],
    related: ["Slack", "Gmail", "Notion"],
    tags: ["automation", "integrations", "triggers"],
    notes: "Compare AI action depth and cost against n8n.",
    source: "Quick capture",
    importance: "Medium",
  },
  midjourney: {
    category: "Image",
    description: "Generative image platform for highly styled visuals.",
    useCase: "Produce concept imagery and brand exploration assets.",
    role: "Visual generator",
    alternatives: ["DALL-E", "Flux"],
    related: ["Figma", "Photoshop", "Canva"],
    tags: ["image", "creative", "design"],
    notes: "Build a reference board for consistent visual styles.",
    source: "Quick capture",
    importance: "Medium",
  },
  notion: {
    category: "Productivity",
    description: "Connected workspace for documentation, databases and notes.",
    useCase: "Publish and organize AI learnings into team-readable pages.",
    role: "Knowledge destination",
    alternatives: ["Coda", "Obsidian"],
    related: ["n8n", "Perplexity", "Slack"],
    tags: ["notes", "sync", "database"],
    notes: "Enable Notion sync for curated learning summaries.",
    source: "Quick capture",
    importance: "High",
  },
};

export const categories: Category[] = [
  "Automation",
  "Coding",
  "Agents",
  "Research",
  "Voice",
  "Video",
  "Image",
  "Design",
  "MCP",
  "Open Source",
  "Extensions",
  "Productivity",
];
